version: '3.5'
services:
  mssql-db:
    image: mysql/mysql-server
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password!1
    ports:
    - 1430:1433
    container_name: bigdata-cluster-mssql-db
    networks:
      - bigdata-cluster-network
  mssql-db-data-load :
    build:  ./mssql-db-data-load/
    command: sh -c './wait-for-it.sh mssql-db:1433 --timeout=0 --strict -- sleep 10 && ./run-data-load.sh'
    container_name: bigdata-cluster-mssql-db-data-load
    depends_on:
      - "mssql-db"
    networks:
      - bigdata-cluster-network
  bigdata-cluster-hadoop:
    build: ./bigdata-cluster-hadoop/
    restart: always
    container_name: bigdata-cluster-hadoop
    command: sh 'start-hadoop-ecosystem.sh'
    depends_on:
      - mssql-db
    ports:
    - "1431:22"
    - "9000:9000"
    - "8088:8088"
    - "9870:9870"
    - "10000:10000"
    - "9999:9999"
    - "9083:9083"
    - "10500:10500"
    - "50070:50070"
    
    networks:
      - bigdata-cluster-network
  bigdata-cluster-mpp:
    build: ./bigdata-cluster-mpp/
    restart: always
    container_name: bigdata-cluster-mpp
    command: sh 'start-mpp-ecosystem.sh'
    ports:
    - "23:22"
    - "9092:9092"
    - "8888:8888"
    networks:
      - bigdata-cluster-network
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "gsivash-db"
      POSTGRES_PASSWORD: "gsivash"
      POSTGRES_USER: "gsivash"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - D:\Users\Дмитрий\PycharmProjects\HadoopClusterDocker\postgres-db\data:/docker-entrypoint-initdb.d
      - D:\Users\Дмитрий\PycharmProjects\HadoopClusterDocker\postgres-db\pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - bigdata-cluster-network
#  bigdata-cluster-nifi:
#    build: ./bigdata-cluster-nifi/
#    restart: always
#    container_name: bigdata-cluster-nifi
#    command: sh 'start-nifi.sh'
#    ports:
#    - "24:22"
#    - "8443:8443"
#    networks:
#      - bigdata-cluster-network
#  bigdata-cluster-elasticsearch:
#    build: ./bigdata-cluster-elasticsearch/
#    restart: always
#    container_name: bigdata-cluster-elasticsearch
#    command: sh 'start-elasticsearch.sh'
#    ports:
#    - "25:22"
#    - "9200:9200"
#    networks:
#      - bigdata-cluster-network
networks:
  bigdata-cluster-network:
    name : bigdata-cluster-network
